// widgets/my-angular-widget/src/main.ts
import { createApplication } from "@angular/platform-browser";
import { provideZonelessChangeDetection } from "@angular/core";
import {
  AppComponent,
  WIDGET_SDK,
  WIDGET_SERVICE_SDK,
} from "./app/app.component";
import type { WidgetSDK } from "./types";

let initialized = false;

export async function init(sdk: WidgetSDK) {
  if (initialized) return;
  initialized = true;
  await sdk.whenReady();
  const widgetServiceSdk = new window.WidgetServiceSDK();
  const host = document.createElement("my-angular-widget-root");
  const appRef = await createApplication({
    providers: [
      provideZonelessChangeDetection(),
      { provide: WIDGET_SDK, useValue: sdk },
      { provide: WIDGET_SERVICE_SDK, useValue: widgetServiceSdk },
    ],
  });
  appRef.bootstrap(AppComponent, host);
  sdk.getContainer().appendChild(host);
  sdk.on("destroy", () => {
    initialized = false;
    appRef.destroy();
    host.remove();
  });
}

// widgets/weather-react/src/main.tsx
import widgetCss from "./widget.css?inline";
import "./setup-dev";
import { createRoot } from "react-dom/client";
import { App } from "./App";
import type { WidgetSDK } from "./types";

let currentCss = widgetCss;
const styles = new Set<HTMLStyleElement>();

if (import.meta.hot) {
  import.meta.hot.accept("./widget.css?inline", (mod) => {
    if (typeof mod?.default === "string") currentCss = mod.default;
    styles.forEach((s) => (s.textContent = currentCss));
  });
}

export async function init(sdk: WidgetSDK) {
  await sdk.whenReady();
  const style = document.createElement("style");
  style.textContent = currentCss;
  styles.add(style);
  sdk.shadowRoot.insertBefore(style, sdk.shadowRoot.firstChild);
  const widgetServiceSdk = new window.WidgetServiceSDK();
  const root = createRoot(sdk.getContainer());
  root.render(<App sdk={sdk} widgetServiceSdk={widgetServiceSdk} />);
  sdk.on("destroy", () => {
    styles.delete(style);
    style.remove();
    root.unmount();
  });
}
