// widgets/todo-carbon/src/App.tsx
import { useEffect, useState } from "react";
import {
  Button,
  Checkbox,
  InlineNotification,
  Loading,
  Stack,
  TextInput,
  Tile,
} from "@carbon/react";
import { Add, TrashCan } from "@carbon/icons-react";
import type { ConnectorsSDK, Todo, WidgetProps, WidgetSDK } from "./types";
import { DEFAULTS } from "./constants";
import { useTodos } from "./hooks";

interface AppProps {
  sdk: WidgetSDK;
  connectors: ConnectorsSDK;
}

export const App = ({ sdk, connectors }: AppProps) => {
  const [props, setProps] = useState<WidgetProps>(sdk.getProps());
  const [draft, setDraft] = useState("");
  const { todos, loading, error, addTodo, toggleTodo, deleteTodo } = useTodos(connectors);

  useEffect(() => sdk.on("propsChanged", setProps), [sdk]);

  const title = (props.title as string) ?? DEFAULTS.title;
  const placeholder = (props.placeholder as string) ?? DEFAULTS.placeholder;

  const handleSubmit = async (event: React.FormEvent) => {
    event.preventDefault();
    const value = draft;
    if (!value.trim()) return;
    setDraft("");
    await addTodo(value);
  };

  return (
    <div className="todo-carbon-root">
      <Tile className="todo-carbon-tile">
        <Stack gap={5}>
          <h3 className="todo-carbon-heading">{title}</h3>

          <form className="todo-carbon-form" onSubmit={handleSubmit}>
            <TextInput
              id="todo-carbon-input"
              labelText="New todo"
              hideLabel
              placeholder={placeholder}
              value={draft}
              onChange={(event) => setDraft(event.target.value)}
            />
            <Button
              type="submit"
              renderIcon={Add}
              disabled={!draft.trim()}
              iconDescription="Add todo"
            >
              Add
            </Button>
          </form>

          {error && (
            <InlineNotification
              kind="error"
              title="Something went wrong"
              subtitle={error}
              lowContrast
              hideCloseButton
            />
          )}

          {loading ? (
            <div className="todo-carbon-loading">
              <Loading withOverlay={false} small description="Loading todos" />
            </div>
          ) : todos.length === 0 ? (
            <p className="todo-carbon-empty">No todos yet — add one above.</p>
          ) : (
            <ul className="todo-carbon-list">
              {todos.map((todo) => (
                <TodoRow
                  key={todo.id}
                  todo={todo}
                  onToggle={toggleTodo}
                  onDelete={deleteTodo}
                />
              ))}
            </ul>
          )}
        </Stack>
      </Tile>
    </div>
  );
};

interface TodoRowProps {
  todo: Todo;
  onToggle: (todo: Todo) => Promise<void>;
  onDelete: (id: string) => Promise<void>;
}

const TodoRow = ({ todo, onToggle, onDelete }: TodoRowProps) => (
  <li className="todo-carbon-row">
    <Checkbox
      id={`todo-carbon-check-${todo.id}`}
      labelText={todo.title}
      checked={todo.completed}
      onChange={() => onToggle(todo)}
    />
    <Button
      kind="ghost"
      size="sm"
      hasIconOnly
      renderIcon={TrashCan}
      iconDescription="Delete todo"
      tooltipPosition="left"
      onClick={() => onDelete(todo.id)}
    />
  </li>
);

// widgets/todo-app/src/App.vue
<script setup lang="ts">
import { ref, onUnmounted } from "vue";
import type { WidgetSDK, WidgetProps, ConnectorsSDK } from "./types";
import { useTodos } from "./hooks";
import {
  SPECTRUM_SYSTEM,
  SPECTRUM_COLOR,
  SPECTRUM_SCALE,
  MAX_TITLE_LENGTH,
} from "./constants";

const { sdk, connectors } = defineProps<{
  sdk: WidgetSDK;
  connectors: ConnectorsSDK;
}>();

const props = ref<WidgetProps>(sdk.getProps());
const unsubscribe = sdk.on("propsChanged", (next) => (props.value = next));
onUnmounted(unsubscribe);

const { todos, loading, saving, error, add, remove } = useTodos(connectors);

const draft = ref("");

const onInput = (event: Event) => {
  const target = event.target;
  if (!target || typeof target !== "object" || !("value" in target)) return;
  const next = target.value;
  draft.value = typeof next === "string" ? next : "";
};

const onSubmit = async () => {
  if (!draft.value.trim() || saving.value) return;
  await add(draft.value);
  draft.value = "";
};

const onKeydown = (event: KeyboardEvent) => {
  if (event.key === "Enter") {
    event.preventDefault();
    onSubmit();
  }
};
</script>

<template>
  <sp-theme :system="SPECTRUM_SYSTEM" :color="SPECTRUM_COLOR" :scale="SPECTRUM_SCALE" class="todo-theme">
    <section class="todo-card" role="region" :aria-label="props.title">
      <header class="todo-header">
        <h2 class="todo-title">{{ props.title }}</h2>
        <p class="todo-meta">
          {{ todos.length }} {{ todos.length === 1 ? "item" : "items" }}
        </p>
      </header>

      <form class="todo-form" @submit.prevent="onSubmit">
        <sp-field-label for="todo-input" size="m">New todo</sp-field-label>
        <div class="todo-form-row">
          <sp-textfield
            id="todo-input"
            class="todo-input"
            placeholder="What needs doing?"
            :value="draft"
            :maxlength="MAX_TITLE_LENGTH"
            :disabled="saving"
            @input="onInput"
            @keydown="onKeydown"
          ></sp-textfield>
          <sp-button
            variant="accent"
            type="submit"
            :disabled="saving || !draft.trim()"
          >
            {{ saving ? "Adding…" : "Add" }}
          </sp-button>
        </div>
      </form>

      <sp-toast v-if="error" open variant="negative" class="todo-toast">
        {{ error }}
      </sp-toast>

      <div v-if="loading && todos.length === 0" class="todo-status" role="status">
        <sp-progress-circle indeterminate size="m" label="Loading todos"></sp-progress-circle>
      </div>

      <ul v-else-if="todos.length > 0" class="todo-list">
        <li v-for="todo in todos" :key="todo.id" class="todo-item">
          <span class="todo-item-text">{{ todo.title }}</span>
          <sp-action-button
            quiet
            :aria-label="`Delete ${todo.title}`"
            @click="remove(todo.id)"
          >
            <sp-icon-delete slot="icon"></sp-icon-delete>
          </sp-action-button>
        </li>
      </ul>

      <p v-else class="todo-empty">No todos yet. Add your first one above.</p>
    </section>
  </sp-theme>
</template>
